#!/bin/bash
# Seed script for teams and students data
# Usage: bash scripts/seed-data.sh

PROFILE="debitech"
REGION="us-west-1"
TEAMS_TABLE="jogafacil-teams-dev"
STUDENTS_TABLE="jogafacil-students-dev"
TS="2026-03-11T00:00:00"

put_team() {
  aws dynamodb put-item --table-name $TEAMS_TABLE --profile $PROFILE --region $REGION --item "$1"
}

put_student() {
  aws dynamodb put-item --table-name $STUDENTS_TABLE --profile $PROFILE --region $REGION --item "$1"
}

echo "=== Creating Progreso Teams ==="

put_team '{"id":{"S":"prog-t1"},"name":{"S":"Sub-8 Progreso"},"category":{"S":"Infantil"},"ageGroup":{"S":"6-8 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"prog-t2"},"name":{"S":"Sub-10 Progreso"},"category":{"S":"Infantil"},"ageGroup":{"S":"8-10 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"prog-t3"},"name":{"S":"Sub-12 Progreso"},"category":{"S":"Infantil"},"ageGroup":{"S":"10-12 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"prog-t4"},"name":{"S":"Sub-14 Progreso"},"category":{"S":"Juvenil"},"ageGroup":{"S":"12-14 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"prog-t5"},"name":{"S":"Sub-16 Progreso"},"category":{"S":"Juvenil"},"ageGroup":{"S":"14-16 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

echo "=== Creating Progreso Students ==="

# Sub-8 Progreso (prog-t1)
put_student '{"id":{"S":"prog-s01"},"name":{"S":"Carlos Mendoza"},"email":{"S":"carlos.mendoza@email.com"},"phone":{"S":"+52 33 1001-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2018-03-15"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s02"},"name":{"S":"Miguel Torres"},"email":{"S":"miguel.torres@email.com"},"phone":{"S":"+52 33 1001-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2018-05-22"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s03"},"name":{"S":"Diego Ramirez"},"email":{"S":"diego.ramirez@email.com"},"phone":{"S":"+52 33 1001-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2018-01-10"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s04"},"name":{"S":"Andres Lopez"},"email":{"S":"andres.lopez@email.com"},"phone":{"S":"+52 33 1001-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2018-07-08"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s05"},"name":{"S":"Luis Garcia"},"email":{"S":"luis.garcia@email.com"},"phone":{"S":"+52 33 1001-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-09-20"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s06"},"name":{"S":"Pablo Hernandez"},"email":{"S":"pablo.hernandez@email.com"},"phone":{"S":"+52 33 1001-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-11-03"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s07"},"name":{"S":"Javier Martinez"},"email":{"S":"javier.martinez@email.com"},"phone":{"S":"+52 33 1001-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-02-14"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s08"},"name":{"S":"Fernando Diaz"},"email":{"S":"fernando.diaz@email.com"},"phone":{"S":"+52 33 1001-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-06-30"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s09"},"name":{"S":"Ricardo Sanchez"},"email":{"S":"ricardo.sanchez@email.com"},"phone":{"S":"+52 33 1001-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2018-04-18"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s10"},"name":{"S":"Eduardo Flores"},"email":{"S":"eduardo.flores@email.com"},"phone":{"S":"+52 33 1001-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2018-08-25"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s11"},"name":{"S":"Oscar Ruiz"},"email":{"S":"oscar.ruiz@email.com"},"phone":{"S":"+52 33 1001-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2018-12-05"},"teamIds":{"L":[{"S":"prog-t1"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-10 Progreso (prog-t2)
put_student '{"id":{"S":"prog-s12"},"name":{"S":"Santiago Morales"},"email":{"S":"santiago.morales@email.com"},"phone":{"S":"+52 33 1002-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2016-01-12"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s13"},"name":{"S":"Mateo Vargas"},"email":{"S":"mateo.vargas@email.com"},"phone":{"S":"+52 33 1002-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2016-04-08"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s14"},"name":{"S":"Sebastian Castro"},"email":{"S":"sebastian.castro@email.com"},"phone":{"S":"+52 33 1002-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2016-06-19"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s15"},"name":{"S":"Nicolas Ortega"},"email":{"S":"nicolas.ortega@email.com"},"phone":{"S":"+52 33 1002-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2016-09-02"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s16"},"name":{"S":"Emiliano Reyes"},"email":{"S":"emiliano.reyes@email.com"},"phone":{"S":"+52 33 1002-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-11-15"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s17"},"name":{"S":"Daniel Gutierrez"},"email":{"S":"daniel.gutierrez@email.com"},"phone":{"S":"+52 33 1002-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-02-28"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s18"},"name":{"S":"Alejandro Peña"},"email":{"S":"alejandro.pena@email.com"},"phone":{"S":"+52 33 1002-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-05-10"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s19"},"name":{"S":"Gabriel Navarro"},"email":{"S":"gabriel.navarro@email.com"},"phone":{"S":"+52 33 1002-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-07-22"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s20"},"name":{"S":"Adrian Romero"},"email":{"S":"adrian.romero@email.com"},"phone":{"S":"+52 33 1002-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2016-10-05"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s21"},"name":{"S":"Ivan Herrera"},"email":{"S":"ivan.herrera@email.com"},"phone":{"S":"+52 33 1002-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2016-12-18"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s22"},"name":{"S":"Hugo Aguilar"},"email":{"S":"hugo.aguilar@email.com"},"phone":{"S":"+52 33 1002-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2016-03-30"},"teamIds":{"L":[{"S":"prog-t2"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-12 Progreso (prog-t3)
put_student '{"id":{"S":"prog-s23"},"name":{"S":"Rodrigo Vega"},"email":{"S":"rodrigo.vega@email.com"},"phone":{"S":"+52 33 1003-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2014-02-20"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s24"},"name":{"S":"Tomas Rios"},"email":{"S":"tomas.rios@email.com"},"phone":{"S":"+52 33 1003-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2014-05-14"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s25"},"name":{"S":"Martin Soto"},"email":{"S":"martin.soto@email.com"},"phone":{"S":"+52 33 1003-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2014-08-07"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s26"},"name":{"S":"Bruno Delgado"},"email":{"S":"bruno.delgado@email.com"},"phone":{"S":"+52 33 1003-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2014-10-30"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s27"},"name":{"S":"Iker Medina"},"email":{"S":"iker.medina@email.com"},"phone":{"S":"+52 33 1003-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-01-16"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s28"},"name":{"S":"Alan Cruz"},"email":{"S":"alan.cruz@email.com"},"phone":{"S":"+52 33 1003-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-04-03"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s29"},"name":{"S":"Kevin Jimenez"},"email":{"S":"kevin.jimenez@email.com"},"phone":{"S":"+52 33 1003-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-06-25"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s30"},"name":{"S":"Raul Dominguez"},"email":{"S":"raul.dominguez@email.com"},"phone":{"S":"+52 33 1003-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-09-11"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s31"},"name":{"S":"Victor Salazar"},"email":{"S":"victor.salazar@email.com"},"phone":{"S":"+52 33 1003-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2014-11-28"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s32"},"name":{"S":"Jorge Espinoza"},"email":{"S":"jorge.espinoza@email.com"},"phone":{"S":"+52 33 1003-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2014-03-09"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s33"},"name":{"S":"Marco Guerrero"},"email":{"S":"marco.guerrero@email.com"},"phone":{"S":"+52 33 1003-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2014-07-17"},"teamIds":{"L":[{"S":"prog-t3"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-14 Progreso (prog-t4)
put_student '{"id":{"S":"prog-s34"},"name":{"S":"Felipe Contreras"},"email":{"S":"felipe.contreras@email.com"},"phone":{"S":"+52 33 1004-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2012-03-05"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s35"},"name":{"S":"Sergio Fuentes"},"email":{"S":"sergio.fuentes@email.com"},"phone":{"S":"+52 33 1004-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2012-06-18"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s36"},"name":{"S":"Enrique Campos"},"email":{"S":"enrique.campos@email.com"},"phone":{"S":"+52 33 1004-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2012-08-22"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s37"},"name":{"S":"Manuel Ibarra"},"email":{"S":"manuel.ibarra@email.com"},"phone":{"S":"+52 33 1004-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2012-11-10"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s38"},"name":{"S":"Roberto Pacheco"},"email":{"S":"roberto.pacheco@email.com"},"phone":{"S":"+52 33 1004-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-01-27"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s39"},"name":{"S":"Arturo Lara"},"email":{"S":"arturo.lara@email.com"},"phone":{"S":"+52 33 1004-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-04-14"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s40"},"name":{"S":"Cesar Rojas"},"email":{"S":"cesar.rojas@email.com"},"phone":{"S":"+52 33 1004-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-07-01"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s41"},"name":{"S":"Hector Zavala"},"email":{"S":"hector.zavala@email.com"},"phone":{"S":"+52 33 1004-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-09-16"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s42"},"name":{"S":"Gustavo Ponce"},"email":{"S":"gustavo.ponce@email.com"},"phone":{"S":"+52 33 1004-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2012-12-03"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s43"},"name":{"S":"Alfredo Nunez"},"email":{"S":"alfredo.nunez@email.com"},"phone":{"S":"+52 33 1004-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2012-02-19"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s44"},"name":{"S":"Omar Velasco"},"email":{"S":"omar.velasco@email.com"},"phone":{"S":"+52 33 1004-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2012-05-06"},"teamIds":{"L":[{"S":"prog-t4"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-16 Progreso (prog-t5)
put_student '{"id":{"S":"prog-s45"},"name":{"S":"Patricio Leon"},"email":{"S":"patricio.leon@email.com"},"phone":{"S":"+52 33 1005-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2010-01-08"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s46"},"name":{"S":"Ignacio Mora"},"email":{"S":"ignacio.mora@email.com"},"phone":{"S":"+52 33 1005-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2010-03-22"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s47"},"name":{"S":"Cristian Avila"},"email":{"S":"cristian.avila@email.com"},"phone":{"S":"+52 33 1005-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2010-06-15"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s48"},"name":{"S":"Damian Cordova"},"email":{"S":"damian.cordova@email.com"},"phone":{"S":"+52 33 1005-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2010-08-29"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s49"},"name":{"S":"Fabian Trejo"},"email":{"S":"fabian.trejo@email.com"},"phone":{"S":"+52 33 1005-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-11-12"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s50"},"name":{"S":"Gerardo Bautista"},"email":{"S":"gerardo.bautista@email.com"},"phone":{"S":"+52 33 1005-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-02-04"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s51"},"name":{"S":"Leonel Acosta"},"email":{"S":"leonel.acosta@email.com"},"phone":{"S":"+52 33 1005-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-04-18"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s52"},"name":{"S":"Ramiro Valencia"},"email":{"S":"ramiro.valencia@email.com"},"phone":{"S":"+52 33 1005-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-07-01"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s53"},"name":{"S":"Saul Estrada"},"email":{"S":"saul.estrada@email.com"},"phone":{"S":"+52 33 1005-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2010-09-24"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s54"},"name":{"S":"Ulises Mejia"},"email":{"S":"ulises.mejia@email.com"},"phone":{"S":"+52 33 1005-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2010-12-07"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"prog-s55"},"name":{"S":"Yahir Sandoval"},"email":{"S":"yahir.sandoval@email.com"},"phone":{"S":"+52 33 1005-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2010-05-20"},"teamIds":{"L":[{"S":"prog-t5"}]},"status":{"S":"active"},"academy":{"S":"Progreso"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

echo "Progreso students created."

# ============================================
# ACADEMY: Gasperich
# ============================================

echo "=== Creating Gasperich Teams ==="

put_team '{"id":{"S":"gasp-t1"},"name":{"S":"Sub-8 Gasperich"},"category":{"S":"Infantil"},"ageGroup":{"S":"6-8 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"gasp-t2"},"name":{"S":"Sub-10 Gasperich"},"category":{"S":"Infantil"},"ageGroup":{"S":"8-10 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"gasp-t3"},"name":{"S":"Sub-12 Gasperich"},"category":{"S":"Infantil"},"ageGroup":{"S":"10-12 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"gasp-t4"},"name":{"S":"Sub-14 Gasperich"},"category":{"S":"Juvenil"},"ageGroup":{"S":"12-14 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_team '{"id":{"S":"gasp-t5"},"name":{"S":"Sub-16 Gasperich"},"category":{"S":"Juvenil"},"ageGroup":{"S":"14-16 años"},"maxCapacity":{"N":"20"},"currentSize":{"N":"11"},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

echo "=== Creating Gasperich Students ==="

# Sub-8 Gasperich (gasp-t1)
put_student '{"id":{"S":"gasp-s01"},"name":{"S":"Liam Muller"},"email":{"S":"liam.muller@email.com"},"phone":{"S":"+352 621-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2018-02-10"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s02"},"name":{"S":"Noah Weber"},"email":{"S":"noah.weber@email.com"},"phone":{"S":"+352 621-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2018-04-25"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s03"},"name":{"S":"Elias Schmidt"},"email":{"S":"elias.schmidt@email.com"},"phone":{"S":"+352 621-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2018-06-13"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s04"},"name":{"S":"Finn Schneider"},"email":{"S":"finn.schneider@email.com"},"phone":{"S":"+352 621-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2018-08-30"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s05"},"name":{"S":"Leon Fischer"},"email":{"S":"leon.fischer@email.com"},"phone":{"S":"+352 621-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-10-17"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s06"},"name":{"S":"Max Becker"},"email":{"S":"max.becker@email.com"},"phone":{"S":"+352 621-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-12-05"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s07"},"name":{"S":"Paul Hoffmann"},"email":{"S":"paul.hoffmann@email.com"},"phone":{"S":"+352 621-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-01-22"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s08"},"name":{"S":"Ben Wagner"},"email":{"S":"ben.wagner@email.com"},"phone":{"S":"+352 621-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2018-03-09"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s09"},"name":{"S":"Tom Richter"},"email":{"S":"tom.richter@email.com"},"phone":{"S":"+352 621-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2018-05-28"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s10"},"name":{"S":"Jan Klein"},"email":{"S":"jan.klein@email.com"},"phone":{"S":"+352 621-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2018-07-15"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s11"},"name":{"S":"Erik Wolf"},"email":{"S":"erik.wolf@email.com"},"phone":{"S":"+352 621-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2018-09-02"},"teamIds":{"L":[{"S":"gasp-t1"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-10 Gasperich (gasp-t2)
put_student '{"id":{"S":"gasp-s12"},"name":{"S":"Lucas Braun"},"email":{"S":"lucas.braun@email.com"},"phone":{"S":"+352 622-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2016-03-14"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s13"},"name":{"S":"Felix Krause"},"email":{"S":"felix.krause@email.com"},"phone":{"S":"+352 622-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2016-05-27"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s14"},"name":{"S":"Jonas Hartmann"},"email":{"S":"jonas.hartmann@email.com"},"phone":{"S":"+352 622-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2016-08-10"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s15"},"name":{"S":"David Lange"},"email":{"S":"david.lange@email.com"},"phone":{"S":"+352 622-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2016-10-23"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s16"},"name":{"S":"Tim Werner"},"email":{"S":"tim.werner@email.com"},"phone":{"S":"+352 622-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-01-06"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s17"},"name":{"S":"Niklas Peters"},"email":{"S":"niklas.peters@email.com"},"phone":{"S":"+352 622-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-04-19"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s18"},"name":{"S":"Moritz Franke"},"email":{"S":"moritz.franke@email.com"},"phone":{"S":"+352 622-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-07-02"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s19"},"name":{"S":"Anton Keller"},"email":{"S":"anton.keller@email.com"},"phone":{"S":"+352 622-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2016-09-15"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s20"},"name":{"S":"Oskar Berger"},"email":{"S":"oskar.berger@email.com"},"phone":{"S":"+352 622-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2016-11-28"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s21"},"name":{"S":"Henri Lorenz"},"email":{"S":"henri.lorenz@email.com"},"phone":{"S":"+352 622-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2016-02-11"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s22"},"name":{"S":"Theo Baumann"},"email":{"S":"theo.baumann@email.com"},"phone":{"S":"+352 622-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2016-06-24"},"teamIds":{"L":[{"S":"gasp-t2"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-12 Gasperich (gasp-t3)
put_student '{"id":{"S":"gasp-s23"},"name":{"S":"Karl Zimmermann"},"email":{"S":"karl.zimmermann@email.com"},"phone":{"S":"+352 623-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2014-01-18"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s24"},"name":{"S":"Lukas Schreiber"},"email":{"S":"lukas.schreiber@email.com"},"phone":{"S":"+352 623-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2014-04-01"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s25"},"name":{"S":"Simon Engel"},"email":{"S":"simon.engel@email.com"},"phone":{"S":"+352 623-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2014-06-14"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s26"},"name":{"S":"Mats Vogt"},"email":{"S":"mats.vogt@email.com"},"phone":{"S":"+352 623-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2014-08-27"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s27"},"name":{"S":"Jannik Seidel"},"email":{"S":"jannik.seidel@email.com"},"phone":{"S":"+352 623-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-11-10"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s28"},"name":{"S":"Robin Haas"},"email":{"S":"robin.haas@email.com"},"phone":{"S":"+352 623-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-02-23"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s29"},"name":{"S":"Florian Brandt"},"email":{"S":"florian.brandt@email.com"},"phone":{"S":"+352 623-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-05-08"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s30"},"name":{"S":"Timo Schuster"},"email":{"S":"timo.schuster@email.com"},"phone":{"S":"+352 623-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2014-07-21"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s31"},"name":{"S":"Nils Dietrich"},"email":{"S":"nils.dietrich@email.com"},"phone":{"S":"+352 623-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2014-10-04"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s32"},"name":{"S":"Lars Kuhn"},"email":{"S":"lars.kuhn@email.com"},"phone":{"S":"+352 623-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2014-12-17"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s33"},"name":{"S":"Hannes Fuchs"},"email":{"S":"hannes.fuchs@email.com"},"phone":{"S":"+352 623-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2014-03-30"},"teamIds":{"L":[{"S":"gasp-t3"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-14 Gasperich (gasp-t4)
put_student '{"id":{"S":"gasp-s34"},"name":{"S":"Marvin Scholz"},"email":{"S":"marvin.scholz@email.com"},"phone":{"S":"+352 624-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2012-02-06"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s35"},"name":{"S":"Dennis Roth"},"email":{"S":"dennis.roth@email.com"},"phone":{"S":"+352 624-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2012-04-19"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s36"},"name":{"S":"Marcel Kraft"},"email":{"S":"marcel.kraft@email.com"},"phone":{"S":"+352 624-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2012-07-02"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s37"},"name":{"S":"Stefan Hahn"},"email":{"S":"stefan.hahn@email.com"},"phone":{"S":"+352 624-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2012-09-15"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s38"},"name":{"S":"Patrick Schwarz"},"email":{"S":"patrick.schwarz@email.com"},"phone":{"S":"+352 624-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-11-28"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s39"},"name":{"S":"Tobias Winkler"},"email":{"S":"tobias.winkler@email.com"},"phone":{"S":"+352 624-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-01-11"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s40"},"name":{"S":"Dominik Bauer"},"email":{"S":"dominik.bauer@email.com"},"phone":{"S":"+352 624-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-03-24"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s41"},"name":{"S":"Philipp Horn"},"email":{"S":"philipp.horn@email.com"},"phone":{"S":"+352 624-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2012-06-07"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s42"},"name":{"S":"Alexander Vogel"},"email":{"S":"alexander.vogel@email.com"},"phone":{"S":"+352 624-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2012-08-20"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s43"},"name":{"S":"Christian Stein"},"email":{"S":"christian.stein@email.com"},"phone":{"S":"+352 624-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2012-11-03"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s44"},"name":{"S":"Matthias Jansen"},"email":{"S":"matthias.jansen@email.com"},"phone":{"S":"+352 624-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2012-05-16"},"teamIds":{"L":[{"S":"gasp-t4"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

# Sub-16 Gasperich (gasp-t5)
put_student '{"id":{"S":"gasp-s45"},"name":{"S":"Andreas Maier"},"email":{"S":"andreas.maier@email.com"},"phone":{"S":"+352 625-0001"},"position":{"S":"Portero"},"dateOfBirth":{"S":"2010-02-14"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s46"},"name":{"S":"Sebastian Huber"},"email":{"S":"sebastian.huber@email.com"},"phone":{"S":"+352 625-0002"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2010-04-27"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s47"},"name":{"S":"Michael Pohl"},"email":{"S":"michael.pohl@email.com"},"phone":{"S":"+352 625-0003"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2010-07-10"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s48"},"name":{"S":"Thomas Eckert"},"email":{"S":"thomas.eckert@email.com"},"phone":{"S":"+352 625-0004"},"position":{"S":"Defensa"},"dateOfBirth":{"S":"2010-09-23"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s49"},"name":{"S":"Markus Schubert"},"email":{"S":"markus.schubert@email.com"},"phone":{"S":"+352 625-0005"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-12-06"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s50"},"name":{"S":"Oliver Kramer"},"email":{"S":"oliver.kramer@email.com"},"phone":{"S":"+352 625-0006"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-01-19"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s51"},"name":{"S":"Julian Albrecht"},"email":{"S":"julian.albrecht@email.com"},"phone":{"S":"+352 625-0007"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-04-02"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s52"},"name":{"S":"Fabian Ludwig"},"email":{"S":"fabian.ludwig@email.com"},"phone":{"S":"+352 625-0008"},"position":{"S":"Mediocampista"},"dateOfBirth":{"S":"2010-06-15"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s53"},"name":{"S":"Daniel Pfeiffer"},"email":{"S":"daniel.pfeiffer@email.com"},"phone":{"S":"+352 625-0009"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2010-08-28"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s54"},"name":{"S":"Kevin Wolff"},"email":{"S":"kevin.wolff@email.com"},"phone":{"S":"+352 625-0010"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2010-11-11"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'
put_student '{"id":{"S":"gasp-s55"},"name":{"S":"Marco Lehmann"},"email":{"S":"marco.lehmann@email.com"},"phone":{"S":"+352 625-0011"},"position":{"S":"Delantero"},"dateOfBirth":{"S":"2010-05-24"},"teamIds":{"L":[{"S":"gasp-t5"}]},"status":{"S":"active"},"academy":{"S":"Gasperich"},"createdAt":{"S":"'$TS'"},"updatedAt":{"S":"'$TS'"}}'

echo "=== Seed complete! ==="
echo "Created: 10 teams (5 per academy), 110 students (11 per team)"
